# Generated by Django 3.2 on 2024-12-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0025_delete_eventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_page', to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPageBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TITLE', 'Title Block'), ('TEXT', 'Text Block'), ('IMAGE', 'Image Block'), ('COUNTDOWN', 'Countdown Block'), ('BUTTON', 'Button Block'), ('BUY', 'Buy Block')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('event_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='eventpage.eventpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
