# Generated by Django 3.2 on 2024-12-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpageblock',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General Block'), ('TITLE', 'Title Block'), ('TEXT', 'Text Block'), ('IMAGE', 'Image Block'), ('COUNTDOWN', 'Countdown Block'), ('BUTTON', 'Button Block'), ('BUY', 'Buy Block')], max_length=20),
        ),
    ]
