# Generated by Django 3.2 on 2024-12-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0002_alter_eventpageblock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpageblock',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General Block'), ('TITLE', 'Title Block'), ('TEXT', 'Text Block'), ('IMAGE', 'Image Block'), ('COUNTDOWN', 'Countdown Block'), ('BUTTON', 'Button Block'), ('PAY', 'Pay Block')], max_length=20),
        ),
    ]
