# Generated by Django 5.1.2 on 2024-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_dni_ticket_owner_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageadress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_payload',
            field=models.CharField(max_length=64),
        ),
    ]
