# Generated by Django 5.1.2 on 2024-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_imageadress_alter_ticket_qr_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uuid',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
