# Generated by Django 5.1.2 on 2024-10-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_creator_event_organizer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='evento',
            new_name='event',
        ),
    ]
