# Generated by Django 5.1.2 on 2024-10-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_evento_ticket_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Employee',
        ),
    ]
