# Generated by Django 5.1.2 on 2024-10-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_empleado_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to='main.employee'),
        ),
    ]
