# Generated by Django 5.1.2 on 2024-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ticket_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ticket_counter',
            field=models.IntegerField(default=0),
        ),
    ]
