# Generated by Django 5.1.2 on 2024-10-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_employee_ticket_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='seller_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_address',
            field=models.CharField(default='https://photos.fife.usercontent.google.com/pw/AP1GczPK2VYQbObxShlqP0dKWIj0ZqtQm1dJ5diNHN3zd6gxE7Lj8TGiCA5jvg=w813-h813-s-no-gm?authuser=1', max_length=200),
        ),
    ]
