# Generated by Django 5.1.2 on 2024-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_event_image_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
