# Generated by Django 3.2 on 2024-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20241108_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sales_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
