# Generated by Django 3.2 on 2024-11-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_event_ticket_sales_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dni_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_tickets', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='main.event')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='ticket_tags',
            field=models.ManyToManyField(blank=True, related_name='employees', to='main.TicketTag'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.tickettag'),
            preserve_default=False,
        ),
    ]
