# Generated by Django 3.2 on 2024-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20241121_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettag',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='password_employee',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_name',
            field=models.CharField(max_length=25),
        ),
    ]
