# Generated by Django 3.2 on 2024-12-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20241123_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='main.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_address',
            field=models.CharField(default='https://i.imgur.com/k4iUzTR.jpeg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tickettag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
