# Generated by Django 3.2 on 2024-12-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20241206_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_background', models.CharField(max_length=500, null=True)),
                ('font_address', models.CharField(max_length=500, null=True)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('image_front', models.CharField(max_length=500, null=True)),
                ('contdown_date', models.DateTimeField(null=True)),
                ('button_text', models.CharField(max_length=25, null=True)),
                ('button_link', models.CharField(max_length=500, null=True)),
                ('button_whatsapp', models.CharField(max_length=500, null=True)),
                ('map_address', models.CharField(max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cbu', models.CharField(max_length=22, null=True)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('text_buy', models.TextField(max_length=500, null=True)),
                ('block_order', models.JSONField(default=list)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_page', to='main.event')),
            ],
        ),
    ]
